version: "3.7"

services:

  server:
    image: gitea/gitea:1.11.0
    ports:
      - "3010:3000"
      - "2222:22"
    environment:
      - RUN_MODE=prod
      - DISABLE_REGISTRATION=true
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    networks:
      - gitea
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints: [node.platform.arch==x86_64]
    depends_on:
      - db

  db:
    image: postgres:12.1
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints: [node.platform.arch==x86_64]

volumes:
  gitea-data:
  postgres-data:

networks:
  gitea:


