version: '3.7'

services:

  gotify:
    image: 'gotify/server:2.0.13'
    ports:
      - '8040:80'
    volumes:
      - gotify-data:/app/data
    networks:
     - gotify-net
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints: [node.platform.arch==x86_64]

volumes:
  gotify-data:

networks:
  gotify-net:
