version: '3.7'

services:

  gotify:
    image: 'gotify/server-arm7:2.0.13'
    ports:
      - '8040:80'
    volumes:
      - gotify-data:/app/data
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  gotify-data:

