version: '3.7'

services:

  prometheus:
    image: prom/prometheus:v2.16.0
    ports:
      - '9090:9090'
    volumes:
      - ./configs/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    deploy:
      placement:
        constraints:
          - node.role==manager
          - node.platform.arch==x86_64
      restart_policy:
        condition: on-failure

  node-exporter:
    image: prom/node-exporter:v0.18.1
    hostname: '{{.Node.Hostname }}'
    ports:
      - '9100:9100'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    deploy:
      placement:
        constraints:
          - node.platform.arch==x86_64
      mode: global
      restart_policy:
        condition: on-failure

  alertmanager:
    image: prom/alertmanager:v0.20.0
    ports:
      - '9093:9093'
    volumes:
      - "./configs/alertmanager/:/etc/alertmanager/"
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    deploy:
      placement:
        constraints:
           - node.role==manager
           - node.platform.arch==x86_64
      restart_policy:
        condition: on-failure    

  cadvisor-x86:
    image: gcr.io/google-containers/cadvisor:v0.35.0
    hostname: '{{.Node.Hostname }}'
    ports:
      - '8088:8080'   
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      placement:
        constraints:
          - node.platform.arch==x86_64
      mode: global
      restart_policy:
        condition: on-failure

  cadvisor-arm:
    image: unibaktr/cadvisor:v0.34.0
    hostname: '{{.Node.Hostname }}'
    ports:
      - '8089:8080'   
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      placement:
        constraints:
          - node.platform.arch!=x86_64
      mode: global
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:6.6.1
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./configs/grafana/config.monitoring
    deploy:
      placement:
        constraints:
          - node.role==manager
          - node.platform.arch==x86_64
      restart_policy:
        condition: on-failure

volumes:
    prometheus_data: 
    grafana_data:

